// ============================================================
// THABISA ADS AUTOPILOT — STATIC DATA LAYER
// ============================================================

const AUDIENCE_SEGMENTS = [
  {
    id: "homemakers",
    number: "01",
    tag: "ANCHOR SEGMENT",
    tagColor: "gold",
    name: "Premium Homemakers",
    subtitle: "Home & Dining — Core Revenue Driver",
    demo: "Age 28–50 · Female · Home-focused",
    interests: ["Home decor", "Interior design", "Table setting", "Pinterest aesthetic", "Competitors: FabIndia, Nicobar, Good Earth"],
    products: ["Table runners", "Dining cloths", "Napkins", "Aprons", "Picnic mats"],
    google: "In-market: Home Decor + Competitor keywords",
    meta: "Home decor interest + Competitor page fans",
    icon: "home",
    priority: "HIGH",
  },
  {
    id: "newmoms",
    number: "02",
    tag: "HIGH ROI NICHE",
    tagColor: "emerald",
    name: "New Moms",
    subtitle: "High Value — High Trust Segment",
    demo: "Age 25–38 · Female · First-time parents",
    interests: ["Pregnancy", "Mothercare", "Baby products", "Organic baby care", "Life event: New parent"],
    products: ["Nursing pillow", "Muslin swaddles", "Mommy bags"],
    google: "In-market: Baby Products",
    meta: "New parent life event targeting",
    icon: "heart",
    priority: "HIGH",
  },
  {
    id: "giftbuyers",
    number: "03",
    tag: "SEASONAL SPIKES",
    tagColor: "amber",
    name: "Gift Buyers",
    subtitle: "Seasonal — Occasion Driven",
    demo: "Age 25–50 · All genders · Occasion driven",
    interests: ["Gifting", "Housewarming", "Baby shower", "Festive shopping"],
    products: ["Gift sets", "Dining sets", "Towels", "Curated bundles"],
    google: "Competitor + gifting keywords",
    meta: "Life events + festive interest targeting",
    icon: "gift",
    priority: "SEASONAL",
    seasonal: "+30% budget 3 weeks before Diwali, Eid, Mother's Day, Christmas",
  },
  {
    id: "urbanwomen",
    number: "04",
    tag: "HIGH VALUE",
    tagColor: "purple",
    name: "Urban Working Women",
    subtitle: "Bags & Accessories — Premium Fashion",
    demo: "Age 25–40 · Female · Working professionals",
    interests: ["Tote bags", "Sustainable fashion", "Minimalist lifestyle", "Eco-friendly", "Ethical brands"],
    products: ["Sling bags", "Tote bags", "Wash bags", "Accessories"],
    google: "In-market: Handbags",
    meta: "Sustainable fashion interest",
    icon: "briefcase",
    priority: "HIGH",
  },
  {
    id: "petowners",
    number: "05",
    tag: "EMERGING NICHE",
    tagColor: "teal",
    name: "Pet Owners",
    subtitle: "Premium Pet Lifestyle — Emotional Purchase",
    demo: "Age 25–45 · All genders · High emotional purchase",
    interests: ["Dog lovers", "Cat owners", "Premium pet lifestyle"],
    products: ["Dog beds", "Cat beds"],
    google: "In-market: Pet Supplies",
    meta: "Pet owner behavior + premium lifestyle interest",
    icon: "paw-print",
    priority: "SEPARATE",
    note: "Keep entirely separate campaigns — distinct creative required",
  },
  {
    id: "retargeting",
    number: "06",
    tag: "ALWAYS ON",
    tagColor: "blue",
    name: "Retargeting Funnel",
    subtitle: "Min 20% of Total Meta Budget",
    demo: "All segments · All demographics",
    interests: [],
    products: ["All SKUs — dynamic retargeting"],
    google: "RLSA on all active campaigns",
    meta: "Dynamic product ads to warm audiences",
    icon: "refresh-cw",
    priority: "CRITICAL",
    layers: [
      { label: "Layer A", desc: "Site visitors last 7 days", creative: "Re-engagement creative" },
      { label: "Layer B", desc: "Product viewers 14 days", creative: "Benefit-focused creative" },
      { label: "Layer C", desc: "Add-to-cart 7 days", creative: "Urgency + offer creative" },
      { label: "Layer D", desc: "Past buyers 180 days", creative: "Upsell complementary products" },
    ],
  },
];

const RULES_ENGINE = {
  scale: [
    { trigger: "ROAS ≥ 3× for 3 consecutive days", action: "Increase budget by 15–20%", confidence: "HIGH" },
    { trigger: "Impression share < 50% AND ROAS ≥ 3×", action: "Raise Google tROAS by 10%", confidence: "HIGH" },
    { trigger: "New lookalike underperforming after 7 days", action: "Shift budget to proven audience", confidence: "MEDIUM" },
    { trigger: "Meta CBO identifies winning ad set", action: "Automatic budget reallocation", confidence: "HIGH" },
  ],
  pause: [
    { trigger: "CPP > target × 2 after minimum spend", action: "Pause ad or ad set immediately", confidence: "HIGH" },
    { trigger: "CTR < 0.8% AND frequency > 2", action: "Pause creative — flag for refresh within 48hrs", confidence: "HIGH" },
    { trigger: "Learning Limited status 7+ days", action: "Pause + rebuild with broader audience", confidence: "HIGH" },
    { trigger: "Budget utilization < 70% for 3 days", action: "Diagnose: check bid, audience size, creative score", confidence: "MEDIUM" },
  ],
  alert: [
    { trigger: "ROAS drops > 40% in 48 hours", action: "Escalate immediately to user", confidence: "CRITICAL" },
    { trigger: "Pixel stops firing > 2 hours", action: "Critical alert — check pixel installation", confidence: "CRITICAL" },
    { trigger: "Account flagged or payment failure", action: "Critical alert — human intervention required", confidence: "CRITICAL" },
    { trigger: "Budget increase > 30% required", action: "Request user confirmation before applying", confidence: "HIGH" },
  ],
  refresh: [
    { trigger: "Frequency > 3.5 on any ad set", action: "Flag creative for refresh within 48 hours", confidence: "HIGH" },
    { trigger: "Video hook rate < 25%", action: "Flag for opening 3 seconds revision", confidence: "HIGH" },
    { trigger: "PMax asset score < Good", action: "Request new creative assets from brand", confidence: "MEDIUM" },
    { trigger: "Lookalike audience > 30 days old", action: "Rebuild from latest CRM purchaser list", confidence: "HIGH" },
  ],
};

const MONITORING_CADENCE = [
  {
    frequency: "Every 24 Hours",
    shortLabel: "Daily",
    icon: "clock",
    color: "gold",
    actions: [
      "Check spend pacing vs daily budget",
      "Monitor CPP trend per platform",
      "Verify pixel health and CAPI matching",
      "Audit frequency across all ad sets",
      "Auto-pause critical ads (CPP > 2× target)",
      "Send anomaly alerts if triggered",
    ],
  },
  {
    frequency: "Every 3 Days",
    shortLabel: "3-Day",
    icon: "bar-chart-2",
    color: "emerald",
    actions: [
      "Full audience breakdown review",
      "Apply budget shifts up to 20%",
      "Assess learning phase exits",
      "Evaluate new lookalike performance",
      "Scale winners: +15–20% budget if ROAS ≥ 3×",
    ],
  },
  {
    frequency: "Every 7 Days",
    shortLabel: "Weekly",
    icon: "calendar",
    color: "blue",
    actions: [
      "Full creative audit across all placements",
      "A/B test result analysis",
      "Bid strategy review per campaign",
      "New audience expansion planning",
      "Rotate creatives running > 21 days",
      "Generate weekly performance report",
    ],
  },
  {
    frequency: "Every 14 Days",
    shortLabel: "Bi-Weekly",
    icon: "refresh-cw",
    color: "purple",
    actions: [
      "Full account audit (Google + Meta)",
      "Product feed refresh and optimization",
      "Competitor keyword review + negative keyword update",
      "Lookalike audience rebuild from latest purchasers",
      "Review bid strategy vs target ROAS",
    ],
  },
  {
    frequency: "Monthly",
    shortLabel: "Monthly",
    icon: "trending-up",
    color: "amber",
    actions: [
      "Customer Match update with latest CRM data",
      "Full strategy review and recalibration",
      "Seasonal calendar planning",
      "Budget reallocation across platforms",
      "Performance Max asset score review",
    ],
  },
];

const SETUP_CHECKLIST = [
  { id: "meta_app_id", label: "Configure META_APP_ID, META_APP_SECRET, META_ACCESS_TOKEN", category: "Meta API" },
  { id: "meta_account", label: "Set META_AD_ACCOUNT_ID (format: act_XXXXXXXXXXXXXXX)", category: "Meta API" },
  { id: "target_cpp", label: "Confirm your target CPP (cost per purchase) in AED / INR", category: "Thresholds" },
  { id: "min_spend", label: "Set minimum spend threshold before pause rules activate", category: "Thresholds" },
  { id: "target_roas", label: "Set target ROAS = 3.0 (300%) in agent configuration", category: "Thresholds" },
  { id: "customer_match", label: "Upload purchaser list to Google Customer Match + Meta Custom Audience", category: "Audiences" },
  { id: "pixel_purchase", label: "Verify Meta Pixel fires Purchase event with value parameter", category: "Tracking" },
  { id: "capi", label: "Confirm Conversions API is active for server-side tracking", category: "Tracking" },
  { id: "product_feed", label: "Ensure product feed is connected and titles are optimized", category: "Feed" },
  { id: "geo", label: "Set geographic focus: UAE + GCC or India metro cities (or both)", category: "Targeting" },
  { id: "brand_search", label: "Create Brand Search campaigns: Thabisa, Thabisa Shop, Thabisa Home", category: "Google" },
  { id: "pmax", label: "Launch PMax campaigns: one per category (Home, Bags, Baby, Pets, Outdoor)", category: "Google" },
  { id: "advantage_plus", label: "Configure Advantage+ Shopping Campaign on Meta", category: "Meta" },
  { id: "retargeting", label: "Set retargeting budget to minimum 20% of total Meta budget", category: "Meta" },
  { id: "seasonal_dates", label: "Input festive calendar: Diwali, Eid, Mother's Day, Christmas", category: "Seasonal" },
];

const BRAND_SAFETY = [
  "Never target low-income audiences — minimum Rs.10L+ annual (India) / AED 8K+ monthly (UAE)",
  "Never use generic or mass-market language in ad copy — always premium, lifestyle, curated tone",
  "Never increase budget > 30% in a single change without explicit user confirmation",
  "Never pause a campaign that has been running < 7 days (learning phase incomplete)",
  "Never target audiences whose profile conflicts with Thabisa's premium positioning",
];
